Readme.md
ethers.nimble
ethers/events.nim
testmodule/testEvents.nim

Byte arrays of size at most 32 are encoded directly into the indexed event arguments.

Decode small byte array

---

ethers/contract.nim
ethers/provider.nim
ethers/providers/jsonrpc.nim
ethers/providers/jsonrpc/signatures.nim

Related to https://github.com/status-im/dagger-contracts/issues/9.
When running tests against a contract deployment on a local Go Ethereum test network, I was consistently getting this error for some calls:
```json
{"code": -32602, "message": "missing value for required argument 1"}
```
The problem seemed to be related to this:
https://github.com/ethereum/go-ethereum/issues/2472
https://github.com/ethereum/go-ethereum/pull/2473
For some Ethereum clients/simulators the [default block parameter](https://eth.wiki/json-rpc/API#the-default-block-parameter) for `eth_call` is optional, but for Go Ethereum it is not.
The test suite for nim-ethers passes with my changes, and the changes allowed me to move forward with what I was attempting re: …

supply block parameter to eth_call, default being BlockTag.latest

---

Readme.md
ethers.nimble
ethers/providers/jsonrpc.nim

Removes `asyncSpawn` in favor of saving a future in `provider.client`, so that any connection errors surface on subsequent calls to the provider, instead of crashing immediately.

Fix crash on connect

---

ethers/provider.nim
ethers/providers/jsonrpc.nim
ethers/providers/jsonrpc/signatures.nim
testmodule/testJsonRpcProvider.nim

Provider now has a method to subscribe to new blocks. 
Equivalent to [`provider.on("block")`](https://docs.ethers.io/v5/api/providers/provider/#Provider--events) from ethers.js.

Subscribe to new blocks

---

ethers/providers/jsonrpc.nim

Ensures that even when a call to the ethereum node to
unsubscribe fails, it will release the memory associated
with the subscription, including the subscription handler
closure.

Release memory when unsubscribe fails

---

ethers/contract.nim
ethers/providers/jsonrpc.nim
testmodule/test.nimble
testmodule/testContracts.nim

Allows `?TransactionResponse`, `Option[TransactionResponse]` etc to be used instead of `Confirmable`.
Figured out how to apply the solution from @Menduist (https://github.com/status-im/nim-ethers/pull/11#discussion_r875539390). Could you review @emizzle?

Allow types that are equivalent to Confirmable

---

ethers/contract.nim
testmodule/testContracts.nim

Dynamically sized return values such as strings and sequences were not decoded as part of a tuple, leading to a difference in byte representation.
Fixes #16

Fix: handle dynamically sized return values

---

ethers/contract.nim
testmodule/test.nim
testmodule/testReturns.nim
testnode/contracts/TestReturns.sol
testnode/deploy/testreturns.js

Allows you to specify multiple return types on a contract call, using a tuple of types.
Fixes #18.

Handle multiple return types on a contract call

---

.github/workflows/ci.yml
Readme.md
ethers.nimble
ethers/providers/jsonrpc.nim
testmodule/testContracts.nim
testmodule/testJsonRpcProvider.nim

When a JSON-RPC call fails, a subtype of`EthersError` is raised.
It used to raise an error type from the `json_rpc` library instead.
Bumping version to 0.2.0, because this is a backwards-incompatible change.
And dropping support for Nim 1.4.x while we're at it.

Raise EthersError when JSON-RPC fails

---

ethers/contract.nim
testmodule/mocks.nim
testmodule/testContracts.nim
testmodule/testJsonRpcProvider.nim

Allows specifying custom transaction properties, such as `nonce` and `gasPrice` when invoking contract calls.
Example:
```nim
let overrides = TransactionOverrides(nonce: some 50.u256)
await writableToken.transfer(address, value, overrides)
```

Allow for custom transaction properties

---

ethers/providers/jsonrpc.nim
ethers/providers/jsonrpc/signatures.nim

Currently subscribing to new Blocks with an external provider leads to an error of 
`{"code":-32602,"message":"too many arguments, want at most 1"}`
That error does not happen with a local ganache or hardhat provider.

Fix block subscription

---

ethers/provider.nim
ethers/providers/jsonrpc.nim
ethers/wallet.nim
testmodule/testWallet.nim

Renames `Provider.sendRawTransaction(bytes)` to `Provider.sendTransaction(bytes)` to be consistent with [ethers.js](https://docs.ethers.io/v5/api/providers/provider/#Provider-sendTransaction)
Does some cleanup around the wallet as well.

Rename Provider.sendRawTransaction and cleanup

---

Readme.md
ethers.nimble
ethers/events.nim
testmodule/testEvents.nim

Add support for indexed (and non-indexed) Event fields types that are distinct `ValueType` or `SmallByteArray`. For example,
```nim
type
DistinctAlias = distinct array[32, byte]
MyEvent = object of Event
a {.indexed.}: DistinctAlias
b: DistinctAlias # also allowed for non-indexed fields
```
1. ~~This is branched off `0.2.0`, commit 16a3d25419ed849cf6791e6537ad5b3736148376, to retain compatibility with `nim-codex`. We should consider rectifying support for nim-codex. See https://github.com/status-im/nim-codex/issues/220 for more info.~~ 
EDIT: Now branched off main and will re-implement support for `nim-eth` in `nim-codex`.
2. ~~Depends on https://github.com/status-im/nim-contract-abi/pull/5, which should likely be merged first, then this PR can be updated so that it does not depend on a …

[feat] support distinct types

---

ethers/provider.nim
ethers/providers/jsonrpc.nim
ethers/testing.nim
testmodule/test.nimble
testmodule/testTesting.nim

Changes the API introduced in #33 to allow for post-fix use of the `reverts` function. Example:
```nim
check await ethCall().reverts("some reason")
```
Changes:
- Removes `doesNot*` functions; you can use `check not` instead
- Removes implicit `waitFor` calls; `reverts()` returns a Future that you can await
- Should work for all providers instead of just the JsonRpcProvider
- Strips the JSON wrapper around error messages in the JsonRpcProvider

Change `reverts` api

---

ethers/contract.nim
testmodule/testContracts.nim

Allows for testing the effects of a contract call on different block heights, for instance on a previous block number, or on the pending block.

Allow contract calls to override the block tag

---

.github/workflows/ci.yml
ethers.nimble
ethers/contract.nim
testmodule/testContracts.nim
testnode/contracts/TestToken.sol

Fixes issue where `msg.sender` for `eth_call` was not correctly set from the connected signer.

fix: eth_call use signers address

---

ethers/provider.nim
testmodule/testJsonRpcProvider.nim

Pending blocks may not contain a block hash and therefore Block.hash should be optional.

fix: pending blocks may not contains block hash

---

Readme.md
ethers.nimble
ethers/provider.nim
ethers/providers/jsonrpc.nim
ethers/providers/jsonrpc/looping.nim
ethers/providers/jsonrpc/signatures.nim
ethers/providers/jsonrpc/subscriptions.nim
testmodule/providers/jsonrpc/testJsonRpcProvider.nim
testmodule/providers/jsonrpc/testJsonRpcSigner.nim
testmodule/providers/jsonrpc/testJsonRpcSubscriptions.nim
testmodule/providers/testJsonRpc.nim
testmodule/test.nim
testmodule/test.nimble
testmodule/testContracts.nim
testmodule/testEnums.nim
testmodule/testErc20.nim
testmodule/testProviders.nim
testmodule/testReturns.nim
testmodule/testTesting.nim
testmodule/testWallet.nim

Subscriptions were already supported for websocket connections. This PR adds support for subscriptions on regular http connections through polling.

Polling subscriptions for http urls

---

ethers/transaction.nim
ethers/wallet.nim
ethers/wallet/error.nim
ethers/wallet/signing.nim
testmodule/testWallet.nim

Wallet now signs transactions according to EIP-155, which includes the chain id in the signature.
Includes a refactor of the wallet signing code.

Fix EIP-155 signatures

---

ethers/wallet.nim
testmodule/testWallet.nim

Adds a constructor for `Wallet` that takes an instance of `PrivateKey`, instead of a string.

Create wallet with PrivateKey

---

ethers/contract.nim
ethers/provider.nim
ethers/providers/jsonrpc.nim
ethers/providers/jsonrpc/signatures.nim
ethers/providers/jsonrpc/subscriptions.nim
testmodule/testContracts.nim

Based on [ethers.js's `queryFilter`](https://github.com/ethers-io/ethers.js/blob/master/packages/contracts/src.ts/index.ts#L1039), allows querying of past contract events, by querying the logs for a contract's event topic.

Query past contract events

---

Readme.md
ethers/wallet.nim
testmodule/testWallet.nim

Uses ~~an optional return value~~ Result to handle invalid key strings.

Handle invalid key when instantiating new wallet

---

ethers/signer.nim

Wrap try/finally around populateTransaction logic to ensure the lock is always released in the case of an error

[fix] Ensure AsyncLock is released in case of exception

---

ethers/blocktag.nim
ethers/providers/jsonrpc/conversions.nim
testmodule/providers/jsonrpc/testConversions.nim

Allows BlockTag to be deserialized from an empty string.

fix: deserialize BlockTag from empty string

---

ethers/providers/jsonrpc/conversions.nim
testmodule/providers/jsonrpc/testConversions.nim

Fixes compilation errors with nim v2.2.0.
First compilation error was a symbol clash for `fromJson`:
```
/home/runner/.nimble/pkgs2/serde-1.2.1-3596e180893eb8035d42cd1d778d2eff8f8fca25/serde/json/deserializer.nim(163, 19) Error: ambiguous call; both deserializer.fromJson(T: typedesc[enum], json: JsonNode) [proc declared in /home/runner/.nimble/pkgs2/serde-1.2.1-3596e180893eb8035d42cd1d778d2eff8f8fca25/serde/json/deserializer.nim(54, 6)] and conversions.fromJson(T: typedesc[E: TransactionStatus or TransactionType], json: JsonNode) [proc declared in /home/runner/work/nim-ethers/nim-ethers/ethers/providers/jsonrpc/conversions.nim(97, 6)] match for: (typedesc[TransactionType], JsonNode)
```
Second error was another ambiguous symbol for `fail` inside the tests.

Fixes nim v2.2.0 compilation errors

---

.gitignore
Readme.md
ethers/providers/jsonrpc/subscriptions.nim
testmodule/providers/jsonrpc/rpc_mock.nim
testmodule/providers/jsonrpc/testJsonRpcProvider.nim
testmodule/providers/jsonrpc/testJsonRpcSigner.nim
testmodule/providers/jsonrpc/testJsonRpcSubscriptions.nim
testmodule/testContracts.nim
testmodule/testCustomErrors.nim
testmodule/testEnums.nim
testmodule/testErc20.nim
testmodule/testGasEstimation.nim
testmodule/testReturns.nim
testmodule/testTesting.nim
testmodule/testWallet.nim

Closes #79 
Modifying the cleanup:
- Ignore exceptions (other than CancelledError) if uninstallation of the filter fails. If it's the last step in the subscription cleanup, then filter changes for this filter will no longer be polled so if the filter continues to live on in geth for whatever reason, then it doesn't matter.
To fix the subscription filter tests:
- `CancelledError` is now caught inside of `getChanges`. This was causing conditions during `subscriptions.close`, where the `CancelledError` would get consumed by the `except CatchableError`, if there was an ongoing `poll` happening at the time of close.
- After creating a new filter inside of `getChanges`, the new filter is polled for changes before returning.
- `getChanges` also does not swallow `CatchableError` by returning an …

fix: modify unsubscribe cleanup routine and tests

---

ethers/contract.nim
ethers/providers/jsonrpc.nim
ethers/signer.nim
ethers/signers/wallet.nim
testmodule/providers/jsonrpc/testJsonRpcSigner.nim
testmodule/testContracts.nim

Concurrent asynchronous population of transactions cause issues with nonces not being in sync with the transaction count for an account on chain. This was being mitigated by tracking a "last seen" nonce and locking inside of `populateTransaction` so that the nonce could be populated in a concurrent fashion. However, if there was an async cancellation before the transaction was sent, then the nonce would become out of sync. One solution was to decrease the nonce if a cancellation occurred. The other solution, in this PR, is simply to lock the populate and sendTransaction calls together, so that there will not be concurrent nonce discrepancies. This removes the need for "lastSeenNonce" and is overall more simple.
This issue was causing issues in Codex's testnet where slots were not being …

fix: nonce too high

---

ethers/contract.nim
ethers/nimshims/hashes.nim
ethers/providers/jsonrpc.nim
ethers/providers/jsonrpc/subscriptions.nim
testmodule/hardhat.nim
testmodule/providers/jsonrpc/testErrors.nim
testmodule/providers/jsonrpc/testJsonRpcSubscriptions.nim
testmodule/testContracts.nim
testmodule/testCustomErrors.nim
testmodule/testErc20.nim

- Fixes `items(JsonNode)` symbol not found when calling `JsonRpcProvider.new` from a consumer. Exporting `serde` from `subscriptions` and then exporting `subscriptions` from `jsonrpc` allowed the symbols to be resolved in the consumer.
- Replaces all instances of `std/json` with `pkg/serde`

fix: `items(JsonNode)` symbol not found

---

.github/workflows/ci.yml

PR make some CI adjustments
- add `status` job which can be used in the branch rules to not stick with the specific matrix job
- set matrix `timeout-minutes: 30` to fail fast, [default](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) is 360 minutes
- added `workflow_dispatch` to be able to trigger workflow manually which is usefully for debugging
- actions updated to the latest major versions
- added spacing between the steps for better readability

ci: add matrix status job

---

ethers/providers/jsonrpc/subscriptions.nim
testmodule/providers/jsonrpc/rpc_mock.nim
testmodule/providers/jsonrpc/testJsonRpcSubscriptions.nim

Adds also support for the recreation of blocks filters.

fix: block filters can be also recreated

---

ethers/signer.nim

Must have been a rebase error...
But this would possibly explain a logic branch that would allow for a missing nonce.
An assertion has been added to ensure that a populated transaction always has a populated nonce.

fix(nonce): indentation mistake after last merge

---

ethers/provider.nim
ethers/providers/jsonrpc/subscriptions.nim
nim.cfg
testmodule/config.nims
testmodule/providers/jsonrpc/rpc_mock.nim
testmodule/providers/jsonrpc/testJsonRpcProvider.nim
testmodule/providers/jsonrpc/testJsonRpcSubscriptions.nim
testmodule/testContracts.nim
testmodule/testCustomErrors.nim

Solves several issues with polling.
Includes 2 fixes in http subscription polling:
- resubscribe when a JSON RPC error is encountered, instead of looking for the string "filter not found" in the error message, because different nodes can have different error messages
- ensure that the polling loop cannot crash, by explicitly annotating the function signatures with allowed errors, and by using `asyncSpawn`
Includes 2 fixes in transaction confirmation:
- no longer allow `.confirm(0)`, because it doesn't wait for any blocks to be mined, not even the block that includes the transaction
- no longer rely on the block number that is reported in the newBlock filter callback, because hardhat is known to report pending blocks there

Fix http subscription polling

---

ethers.nimble

Also bumps ethers patch version

chore: updates non-versioned deps to their versioned counterparts

---

.github/workflows/ci.yml
Readme.md
ethers/contract.nim
ethers/errors.nim
ethers/provider.nim
ethers/providers/jsonrpc/errors.nim
ethers/providers/jsonrpc/subscriptions.nim
ethers/signer.nim
testmodule/providers/jsonrpc/rpc_mock.nim
testmodule/providers/jsonrpc/testJsonRpcProvider.nim
testmodule/providers/jsonrpc/testJsonRpcSubscriptions.nim
testmodule/testContracts.nim

Introduces breaking change to API, where subscription handlers now return Result type. Handlers, similarly to now will be called with events wrapped in the Result when new events are detected, but also handlers will be called when some error in the underlying event detection mechanism is detected.

feat: subscriptions get passed result questionable

---

ethers/providers/jsonrpc/subscriptions.nim
testmodule/providers/jsonrpc/testJsonRpcSubscriptions.nim

Unsubscribing from a non-existent subscription as well as duplicate unsubscribe should have no effect (harmless).

fix: http unsubscribe

---

config.nims

With [testutils 0.6.0](https://github.com/status-im/nim-testutils/commit/94d68e796c045d5b37cabc6be32d7bfa168f8857) released, we can re-active the style checking (see https://github.com/status-im/nim-testutils/pull/54).

chore: re-activate styleCheck
